Ns3Env parameters:
--simulationTime: 60
--openGymPort: 5849
--envStepTime: 0.05
--seed: 100
--testArg: 0
--adj_mat_file_name: /home/tdasilva/PRISMA-master/prisma/examples/abilene/adjacency_matrix.txt
--node_coordinates_file_name: /home/tdasilva/PRISMA-master/prisma/examples/abilene/node_coordinates.txt
--node_intensity_file_name: /home/tdasilva/PRISMA-master/prisma/examples/abilene/traffic_matrices/node_intensity_normalized_0.txt
--LinkDelay: 1ms
--MaxBufferLength: 16260B
--load_factor: 0.4
--linkFailureTime: 25
Creating link between switch nodes
12     11    1     0
14     13    2     0
16     15    3     0
18     17    4     1
20     19    5     1
22     21    4     2
24     23    6     2
26     25    7     3
28     27    8     4
30     29    9     5
32     31    7     6
34     33    9     8
36     35    10     8
38     37    10     9
Size switch_nd :39
Configuration of time based alert
Simulation start
Node: 0, GetObservationSpace:  BoxSpace Low: 0 High: 100000 Shape: (4,) Dtype: uint32_t
Node: 0, GetActionSpace:  DiscreteSpace N: 3
Simulation process id: 189140 (parent (waf shell) id: 189029)
Waiting for Python process to connect on port: tcp://localhost:5849
Please start proper Python Gym Agent
/usr/local/lib/python3.8/dist-packages/networkx/convert_matrix.py:686: DeprecationWarning: from_numpy_matrix is deprecated and will be removed in NetworkX 3.0.
Use from_numpy_array instead, e.g. from_numpy_array(A, **kwargs)
  warnings.warn(
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
Node: 1, GetObservationSpace:  BoxSpace Low: 0 High: 100000 Shape: (4,) Dtype: uint32_t
Node: 1, GetActionSpace:  DiscreteSpace N: 3
Simulation process id: 189140 (parent (waf shell) id: 189029)
Waiting for Python process to connect on port: tcp://localhost:5850
Please start proper Python Gym Agent
/usr/local/lib/python3.8/dist-packages/keras/layers/core/lambda_layer.py:303: UserWarning: models is not loaded, but a Lambda layer uses it. It may cause errors.
  function = cls._parse_function_from_config(config, custom_objects,
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
Node: 2, GetObservationSpace:  BoxSpace Low: 0 High: 100000 Shape: (4,) Dtype: uint32_t
Node: 2, GetActionSpace:  DiscreteSpace N: 3
Simulation process id: 189140 (parent (waf shell) id: 189029)
Waiting for Python process to connect on port: tcp://localhost:5851
Please start proper Python Gym Agent
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
Node: 3, GetObservationSpace:  BoxSpace Low: 0 High: 100000 Shape: (3,) Dtype: uint32_t
Node: 3, GetActionSpace:  DiscreteSpace N: 2
Simulation process id: 189140 (parent (waf shell) id: 189029)
Waiting for Python process to connect on port: tcp://localhost:5852
Please start proper Python Gym Agent
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
Node: 4, GetObservationSpace:  BoxSpace Low: 0 High: 100000 Shape: (4,) Dtype: uint32_t
Node: 4, GetActionSpace:  DiscreteSpace N: 3
Simulation process id: 189140 (parent (waf shell) id: 189029)
Waiting for Python process to connect on port: tcp://localhost:5853
Please start proper Python Gym Agent
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
Node: 5, GetObservationSpace:  BoxSpace Low: 0 High: 100000 Shape: (3,) Dtype: uint32_t
Node: 5, GetActionSpace:  DiscreteSpace N: 2
Simulation process id: 189140 (parent (waf shell) id: 189029)
Waiting for Python process to connect on port: tcp://localhost:5854
Please start proper Python Gym Agent
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
Node: 6, GetObservationSpace:  BoxSpace Low: 0 High: 100000 Shape: (3,) Dtype: uint32_t
Node: 6, GetActionSpace:  DiscreteSpace N: 2
Simulation process id: 189140 (parent (waf shell) id: 189029)
Waiting for Python process to connect on port: tcp://localhost:5855
Please start proper Python Gym Agent
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
Node: 7, GetObservationSpace:  BoxSpace Low: 0 High: 100000 Shape: (3,) Dtype: uint32_t
Node: 7, GetActionSpace:  DiscreteSpace N: 2
Simulation process id: 189140 (parent (waf shell) id: 189029)
Waiting for Python process to connect on port: tcp://localhost:5856
Please start proper Python Gym Agent
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
Node: 8, GetObservationSpace:  BoxSpace Low: 0 High: 100000 Shape: (4,) Dtype: uint32_t
Node: 8, GetActionSpace:  DiscreteSpace N: 3
Simulation process id: 189140 (parent (waf shell) id: 189029)
Waiting for Python process to connect on port: tcp://localhost:5857
Please start proper Python Gym Agent
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
Node: 9, GetObservationSpace:  BoxSpace Low: 0 High: 100000 Shape: (4,) Dtype: uint32_t
Node: 9, GetActionSpace:  DiscreteSpace N: 3
Simulation process id: 189140 (parent (waf shell) id: 189029)
Waiting for Python process to connect on port: tcp://localhost:5858
Please start proper Python Gym Agent
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
Node: 10, GetObservationSpace:  BoxSpace Low: 0 High: 100000 Shape: (3,) Dtype: uint32_t
Node: 10, GetActionSpace:  DiscreteSpace N: 2
Simulation process id: 189140 (parent (waf shell) id: 189029)
Waiting for Python process to connect on port: tcp://localhost:5859
Please start proper Python Gym Agent
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
